rules:
    - name: ENC[AES256_GCM,data:wlwwlJUL,iv:74VgvPvbyucpGyuSaAHq1j4v6FCs/HoxzbEOCM1H8BU=,tag:b5YnKuhwG4t6jLFYmJhu+g==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:Z+rjdX8BhpaCIg==,iv:I/knEjbkhvId2u9knzaglvH94WAQmSq6XM5mMxKysyk=,tag:mx4JOcx8hMCySy/Q5N/HUg==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:2X9BY8WYgrI7MBg0f8JCcohI5CoPKTSKYwolB9oD81XlQJTURyL8S1q61np1U1A1DL8LsfGHcUJgZldgKw==,iv:9AfvFPepdwd1yTAYphiwMUc7Cn6gIVYzgqPL0LCmjMs=,tag:BhAMtL5EmJYTOm/OgD6ORg==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:L3t/PxpXIrorXW3XRwVy/+97mUeNpzOcAWvs,iv:1SRelsgCHvspmqvUIAf3DKOgAdMQ8yP/sNHDu0oXSSk=,tag:V7jOsWzYdbxlo9l16bg+yQ==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:KjGjQJSpNZYP1n5j1QX8Mg==,iv:rbDuBjkD2zIYC1LzVhPZhjB4m0lwc5gbNsVJ35SsWcU=,tag:/AqP0ogARMQBo5fSjp14zQ==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:fEgRAaNG1w==,iv:laT06mIyi1ZyVrZAyg401TRKMatha8cZ3EqKbEUMXYs=,tag:x4I7vNEruHzm8y/L9r3psQ==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:uaHdAeBCspzWqZjSvhwxzJ3b4Z90YvfUvqO0Al+inLt4J1+DHgRUEZE5QpzYH1Jcf2qOq49cjz3C1tKCCidyLFhFSPFjyRBtGShJ37J1oBtMWf4OiJV/YdM1TprRnMheLdciUt3Hr7U0dbTfwfAJYyxH,iv:vrtmMnafeLyYHvVgPaNJJ2Kcmp1xKMtPZfl96Y7/Mvk=,tag:yaqYMJO5KMadDm/3V5NUpQ==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:+xsNugKrSMmS0SI/h6PKeS5mVz6buzDyOmnl9hIQ4wfsoWzJe87saQ+ES2eADOt7aXrOxqQ4s41SsgfI117XIL7+7RveYdhhqrULUjAw0azyrDJFS3GnxPdXgCc+iFbSai+hdP/IkQs=,iv:dCB6Uyc/NWX1s0Tw8YYHUpqsFSQJBltPQJrEEKpk8jc=,tag:Cdt9KC9MHNWTpdW8trRNkw==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:cNTxXkHAJlYUqbN4gjen,iv:b0i8ISbXLjRUt2EnBXDoUKf48+BZn1t168ZEoGjp2U8=,tag:D6nfl//vXbrOVn5+uXbmHg==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:fEgRAaNG1w==,iv:laT06mIyi1ZyVrZAyg401TRKMatha8cZ3EqKbEUMXYs=,tag:x4I7vNEruHzm8y/L9r3psQ==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:FzDu6wvIXNFkMEpPS3slLNWAcYjV5J+qzW9WbNZa7mc7VM3uCS/bRfm/egK/vKm5MY1VnsWpZPf4CIp2CCz5ppqNGlUn7Wdgv6+WxZTmtSd+8omloI6D2vNbBHxbUylo,iv:UU3FbtBg6xJD+6t/JUBNm/TebegMYeXU4aHOQyY5Pu8=,tag:1qBwHCFYEl39P6W2opq+Nw==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:yAJGU2V/waGkKnM7vrGx3pPn2ybXdBCU5p8C6JUO8p2U6VgNRa4UYr3fESvi6//1xOweh8ucjDqlkGSuWY+DWZJnik2Wjaua12OYKcVskg7o3bZFvioHSBOqaQH0Wabm3NrWMi3kIa4=,iv:3Rh9T7mkQjt9uhesgLmexDjn1SGbDDRK79KnDN4C2HI=,tag:zDcOtcGe/aT0NJwTdAu4KQ==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:4vIU,iv:/5+8qZkmOaVrXlvKZNr36m9fySw/jF+TpAt3I3y6B8Q=,tag:PCcQDzReyuqqGo095H6xHw==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:Nhch,iv:ltY1FY2eeySIoFBI0yHwvApyZRgku2ozlCsm7XRHGQo=,tag:NLT/AQcBeZy2Q9d201FsPQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:cbPb,iv:YqkdRHCGlzNtnL/T+Fvv/AobloXHhy4DpBERlGQh0KU=,tag:F2kPy0PNiERzo186zo70Qg==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:mXXJf4m7imgUEbKN+x/eijJ3mPq8Eu2kUilS2m1epUGFZiWCZ/7hxIuTeqMRiXo7P1rbgNfV02xVKGy9eLMQanb45RCDP3Kxq0qlKzi0gPAIZ3DdFjTdLZQydJHfFfE7OUeB,iv:lAjw9IhARrs/aYt9yCW0GOmL7qkRIFXdqtbQiWUrEs8=,tag:Fe9k03aDUPsBGmkG2fnR0A==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:eLlJbZaI/m+95zqJmCFVclCfRFZf/cUBqeJxQ76d+EY3QpX4DJBB8mSwvb1ZxlWqSid+3ujteUeBJzGJA8QFCDxQN1xKcRPbBcC/KFma1sVAZ+HTrUu8lcaUpmtbrwRVIubTPSBWqtQUGwQL6W3bn39WrEA=,iv:LYTOAnI4x2c8xsu/pTr8n8kn5Td0lpDXOSF1nHQEoPc=,tag:7RLnmYUfBs3tTPwJXGXOAQ==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:X1pjFHQJjxRxGRZK/y8NrgwWZOFYSG4Ro58+/zviYw==,iv:vzmb+/Izokd1GaH6Xppj60P3EmpZ6v1aR494XwQ+RzI=,tag:J7PccKYbR23dr0+2i5Zjkg==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - regex: ENC[AES256_GCM,data:1y4dJM9kuOIiNAnkcmWPIkttZNdXH8TFkek1bKWcdhTfd88v6e66zmXUOg1etbA/mbMpbIc9knMyc9Ap8eHI,iv:ONTZd4C0ZgFsWqH8LehAPrinHut/L7WPOlnDzRzTaDY=,tag:yK7Gt/4LpPbKkHmu+lvPEQ==,type:str]
        - python: ENC[AES256_GCM,data:JsaOZUY/I5rCqNmLUe/mPMzfZ6qfZigx6ua5BybnmHu9CSFrN7vC84ako/Sfa6eIqaUDnCT6aAnFNaCgQ5PkfTe4TENfaDTnVZ6kJkTtvtxGwqAch9ctVKPEoSvWbCFVGL3I5w8PhvGVkSVy6U/A+OPoXxAJ56vUD+M9Ik3GBbB8UFs8NAyirGNUran0kRljWv1r8vaf4mmpldo9oUk2bdAFY0muVf+fzRTHohfbpqmM+1tNUgUgb38Gq4G1YrjE9svhCK5nuUtrXAzAiTiiZrXA9L2W3ttmenGo6SRkLtJOdi9ZE9HGc6jX3ahQFvw6KpbEyHFP71mnSBSFm67lDSwDNU73NDNc0KgdMdsXIsSg6dXCwHNmjCTPCtUlYlkPNOwhII+CSbPvhufKzRnUGBdSGPDeCuK8gMTSfMZevCtAL7PsDSNQ5PZwzhIzP3/m,iv:o3TFHymOUnzSQOnB8sfUY0ccBietJUB24KuylAT6oGg=,tag:WPvBOe49eNByuqPxluTV2g==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:lKKBSL8hukFLFFqclwJlAp7n6DVI9+hozkWAl81Mcc8pQvAYsV4BOgTRvq0kfwKNKEqA2TzMflE0pxwGpF1QccJXUnpwOJqZfwucxPSpJYV91w==,iv:wNAgcP0mNVq9T4bPgsitZqDleJsEmwX7qMXLGdnnnj8=,tag:CsTaC1HnLj7T/A7CJZO+JA==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:vDZGu3H4xviwp8GGwINSrkyGqVReK2dDm3yxQw==,iv:st0rTJjnIOa18TzWBSbvbb+JoHvvyKEy8r68NwMek64=,tag:baXtOBlyviy0MPPLLm/9hQ==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:EqYXXPijZKbviD/+bhuuUrVzz0CbH4IM,iv:CZq8ZPZLqyfiZ6Si6rOXvb5GxHQHtwHu/E2UCDcDkNk=,tag:6sG7esICnQBemdbS3NK03A==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:vYwzYrLhn+60M+hFtOG6HY1CRhS8f6Aax2wjErOlPM8ii4C4xyOoeKZlXbZBgfG9N7sAhTOe7DDZca5AVcvu9MvVFY8nKKPZe3E=,iv:F+E4v7cBrAdlBo/GOg4M5dht+D3KHyq+lfAPH6oGgtA=,tag:0zExdVNjj73XgxSHNL2eyQ==,type:str]
        - python: ENC[AES256_GCM,data:DgbHEFPuJicIgCffOODGDL/DfXYYWSaHMo9ZnXbUZ6/eq5g6iYJSsb1haWt3+I2mCr1i8i5p7XXNBxGc0qEmTb+Ef4dbLYNlB7xor2TIzoWB62pY0Ffr/l9GCaYtnlkGc0cq5X/ajNz6PFT6mP+FPlsMcHFQ9qvlsfbcr2Sw+Fz1u0N9xhh6blMoQCXJhhKGQPA5WwMrgyBl/bvPc0Hlu/39MLSVXw==,iv:5jFhcVJ16t50Zd/GtXVIQEtVtKIDkgPWD4fUgp491nQ=,tag:Ai17bLpmo0p2tACNOK1waQ==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:LnQ5ZzB1tcLbvXTBzGTUb0nDnYT+fAQyInU3t6M2sD8ikscQgIP7sQf9Crtp52Kyvg6ZGS+2JYmEZlWXcd6qzDbY7+/jasBQBDMqE88flX4h,iv:ltXwD9Kin7iP1oVnH6VxSn/lZ6Ahon45b2ekOeRcAps=,tag:stOry07SKpbWWSTA48kEug==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:uZiOoAuu7Akbmi0dsAO9sAkPr8ea56DbQjbceTkfj1QZgenluZvJ,iv:VDDoSfndzB7yZDx/24v1paPudsBZDEmhrpdkY+Tm/iE=,tag:B4Btdyh4waW9XWuuV/BURw==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:EqYXXPijZKbviD/+bhuuUrVzz0CbH4IM,iv:CZq8ZPZLqyfiZ6Si6rOXvb5GxHQHtwHu/E2UCDcDkNk=,tag:6sG7esICnQBemdbS3NK03A==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:RtV4OCJMHPGkparxr+Sd6+RmonusrrQYQCGqxUkgo38MVfr6Gy3mOSP9H6QtAYnSGKrKchF758Xh3pXhKg==,iv:0gpstqLMb8c14h5Oe+yQMJc4VdkHfYwGpTq18boo1PA=,tag:i4C6ReTSpkJ8iV/mk8Z8aw==,type:str]
        - python: ENC[AES256_GCM,data:DdgIJ3ndnw9rE1OQVIvFvfnpXtqOje/ncaX/Bz2eiBCRHof+D7RrvnxpX3PaBdMze0m+ErJq8vRGzFqpVZ+WIlvcYKk3/LetZJDwfnE4ymqgvvvsxcTRvAgWV91teu8QFXI/MUl5MbNrgFTzkrr3jh+f91G0URt94gTRI1WZZyblqNGyo5n1XlCZyLfPn3mE4Irhh+LdytJZzzszsHh1arDeG7F7u3VIWyTAnyB+WP7wHOYoriV9OjjCh9ieHdTDV91KPy4eZzsd/cWVJ4Eg2Gxi,iv:02O985y/dw/deYJU4irKSQ3gGE2iKt/On4SAckrf+T4=,tag:Fo01P2ObHJVtX4C/J6DxSA==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:304i4s9xit6mCegJUkMwBgRKgJoDzMJ6V1ItSVsS/9IW6HMTyRuhkKEvDOM3tfOqsy5QkzunFZlb80yB3heT4ygNc3vl9RLE3Rx9b/eAUmj0nJSwWM/H+AT4rQ4=,iv:TEaOlujJna6wkG0qR4+8z4XcW71cInR/jok9ebJB/AU=,tag:Wk21LcUAa1iJwYWy+Vnx8w==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:dylpu4FHnqIdN7rt0+Ps5/wkQ5Jb/Hla4h93IiUEF+cwZk22il0j,iv:Iv49ysmEMusUOIk4quOZFIDu1ygFvAF7X8E9fTLoEP0=,tag:e7RHoJuEvDuMD1muJaZGJw==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:EqYXXPijZKbviD/+bhuuUrVzz0CbH4IM,iv:CZq8ZPZLqyfiZ6Si6rOXvb5GxHQHtwHu/E2UCDcDkNk=,tag:6sG7esICnQBemdbS3NK03A==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:aTHRz+CMjTTECdhUHm0d3krIc0qQTnh4/OiO9Y/v1t/89F+XrKu9wNwnBEkF2e9fAsbM9UHYKQO+xi59N9RF/w==,iv:NDhqhu/+MujI2n8siofF4ZGyKipGXPBKoJcV5+nS9Qw=,tag:n7IvQ+gB0RwnOAws2c+5lQ==,type:str]
        - python: ENC[AES256_GCM,data:DdgIJ3ndnw9rE1OQVIvFvfnpXtqOje/ncaX/Bz2eiBCRHof+D7RrvnxpX3PaBdMze0m+ErJq8vRGzFqpVZ+WIlvcYKk3/LetZJDwfnE4ymqgvvvsxcTRvAgWV91teu8QFXI/MUl5MbNrgFTzkrr3jh+f91G0URt94gTRI1WZZyblqNGyo5n1XlCZyLfPn3mE4Irhh+LdytJZzzszsHh1arDeG7F7u3VIWyTAnyB+WP7wHOYoriV9OjjCh9ieHdTDV91KPy4eZzsd/cWVJ4Eg2Gxi,iv:02O985y/dw/deYJU4irKSQ3gGE2iKt/On4SAckrf+T4=,tag:Fo01P2ObHJVtX4C/J6DxSA==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:LFNMoawRhnK4z1eOdEG8aT7Ad+t5knvUwIZhGdLnz95cUMJLFvZy7SVaFod0iOZsJWLsD5S8n0v+evUDDvGPTuyQ32rC3J1upl5FCC9/8M2cu2mcPU/CnONTMVI=,iv:uF5vr7LLOwAZzXxV8gN8YuaGiVwd+53QESnGzFy/+o0=,tag:VquxdhHC7Xf2+Xy1bfPOdw==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:YC+2/ppz85EuK4d7OEH7kH5/BKEu2QCz,iv:0eyQ6GK8S9Zk70vJRzZ/ijH7bidFI55Dl1t2msygW4M=,tag:22Ng+72TITNjGwQmBLCB0g==,type:str]
      locations:
        - ENC[AES256_GCM,data:pPSTrosXRUV+,iv:fw89SdD6WGY7RckoLbOns7mUD1s3XNJZ27SGUoUK2po=,tag:KZiFQLsPJv5sHfw64xI/FQ==,type:str]
        - ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            startswith: ENC[AES256_GCM,data:RCC4oYNTJA+wY902QM1F,iv:rbMDu6FTmitJajjSLZ9py+rMNObdsIVHbfrr9BsRz9c=,tag:5OXbUlYfaf+VeAVSoGBzDQ==,type:str]
      actions:
        - move: ENC[AES256_GCM,data:YUMFVOxQeGn8i0N4kUZTYz9aqT0j/LKB6Sg=,iv:Bcff880z5iDMvd3vI1Z5tDBAvrarNOQ0kTAhvwZxZrg=,tag:PpwrY2rQCqvY3YaNXHmAhQ==,type:str]
sops:
    age:
        - recipient: age1y7g3ehjwu055n3h0vz0yvudnh4p0tu849m2q64juxt9qxvpvt39q6z63la
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN1NIL2g5RVRiWUw5M3p6
            eUxlN0pWOVVUby92ZW9HVUpDeVlqajJCbEY4CmNFVHJnU3JkWFg5aCs1OE14NjN2
            NWZoeFd6L0M3VnlPNTNRSXVmU0N2bk0KLS0tIExlbDNpVFBaVWVnc2xpNjZIYTN2
            SUdjbjRPbmZSMFZCWVBZNVZpNFZKd2sKdntmxla9crG8ir+3GonHfYHp42Lbzikh
            Xljz8ruXlxeayKqF0/8CQDc0brNQ8mI+p6xrCjfGo1xmiOmMPHYkFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T20:15:06Z"
    mac: ENC[AES256_GCM,data:Zcd0AKKI55iByKgiUfDSmNJSGtCC0AulYclr5nolU53D4rucoLICmH5IyyaSJhmyNPeF/4ZEgzt/Z1oyPSnMpE7haKH+pjGWrIsdXaVJJqFQaGJsCGeMn2BCGpHjedRUJpYuDUA0oVe1kc6cNRx4MGbxr5cwvNwtQBPuuquqZO8=,iv:SIh25zpXyoGuc2uVrBSSqA5vmI1Mb3nlrkJYEkiTVbk=,tag:k05OKnbZUDmGQdfjcXLpGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
