workEmailPositive: ENC[AES256_GCM,data:rlFB4PPYKVB2syGLSwpPV9no,iv:f1iXhMu0Jw0sxzlbo/l11uEJ5y8ZfQXdYWuEtJq0ojw=,tag:5PdFEOIaU/SBnV99q8bdvA==,type:str]
sops:
    age:
        - recipient: age1y7g3ehjwu055n3h0vz0yvudnh4p0tu849m2q64juxt9qxvpvt39q6z63la
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVFFyditwalcyck84YkVD
            QlBFK3RkQkFFdzlZL1BoRDZHRXd2a3UzaVJjCmRleXVRamRCazk2aE1qck5qaFIv
            SDFaMjlwS1FsdmJHL0RyZnI4NzZvZE0KLS0tIENpQ2o4NE1sdXUrY0ZPcEt6MW5a
            UnVuY29VSVI0SVUrcndkRTBpbG1EUTAK22zmWYzlw0Y/2EXeck5tPp2M/JpOpeC+
            4QvV1LawdnKFqvNSdcehYXos9cTKOJ/giT0w5qodo+VN8n4aFrRJKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lew4ss8hkajwt57ycwy33j385jrc6ftle29hr0ux089w8ycf0udq4myxpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVXFSWDA4ajBCOTZUZmVu
            aXhVQWZQU3pObkdYT3hZUlFLVnlybFdzVFg4CmVhMVdHSElrcnkwRjB6OEw5VzNK
            bklNRG4rOVVIcElJeTZRZ1dzb250U0UKLS0tIGs3WTIxdTczODFSNi9YWlBBY25T
            TjN6aDc4c1BZckFEbm9DTzBHWXIwM1kKOzz1j9+kLKa3NPLj3HBFzVHtT4/QP49J
            2foJTcCMPIYCFLCnYWhnMHMC74hchEH7ezRuGZ/A5qznI7T5GGOUBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T22:15:17Z"
    mac: ENC[AES256_GCM,data:2Sk0EyZpfOXhQqEBczs2iOQixD3nsfvFF/Ywbpw4DvsMtkin0t0PQn7GZq679Xa4DoxCemWQgOcrcpo5RY7DfG1EtnOosYHd0/iaRaHjIv6WYzZc355cm8ONq1DuyWQc50+8ouHqcg48OuaDLYiJTQdUHSxY5TgJjg1k0oQwfK4=,iv:zzA10FBGmqw6Ag9iW/xBRStUnrOVM6L2akSY+FBximE=,tag:8wTx36Dg4383wZweofjRHg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
