workEmailLeanlab: ENC[AES256_GCM,data:9k7YdPO6gTAAZ8iaxMl+8f5/,iv:PaeHx0Z4AVTNL2iEWG4U/4aM5pc2yTQnYO340MziRLE=,tag:h5A9QnePMq5m3Yp/my5ZZA==,type:str]
sops:
    age:
        - recipient: age1y7g3ehjwu055n3h0vz0yvudnh4p0tu849m2q64juxt9qxvpvt39q6z63la
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSUNyWExkSTdvMGhvRFh3
            ZHh2b0J4L3pPOUY2UzZTeWZPV2llVjlGcUFZCnByREVJVC9mOUhLc3RJL0lySUp4
            aktxUzF3SHlFcVlSVXlXRFg0a0J6RmcKLS0tIEo2UnVYWktyMHU1TnFDUnpoWi9R
            TFlWWkJuaVlJNUN5WjVPamFqbmF4TTAKZU2DhQP/5GlFzPn+2AjRgHx8QPl0bCtb
            2ZKKFO4CG1ejig3t9dLQesavDqLpZ4tX1Tl+BgQCJbhBTVLMax/xWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T17:16:25Z"
    mac: ENC[AES256_GCM,data:iC39v7LPK8p69NFCpWDKQr+fh5uypBaVpL0VRzQYmnnRdFO+jdl5HmuS6SZ2caPKnslBxGOG1tiIS7LAIHFsdjpF/U8xUtBFwvJaKxUAybQ+6f1KgskQFhXc4wQJJ8Jtwm0t1d/BL44Bh5P6a8AZomZAi9djPBF1PejVN75yzQM=,iv:qfkADFPy4eqI5M6zPVI/qBWUqTUTUvSP5yGdSBPce0E=,tag:ZCCFnk9VA+E52eO32z9FMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
